apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescripto-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescripto-frontend
  template:
    metadata:
      labels:
        app: prescripto-frontend
    spec:
      containers:
        - name: frontend
          image: prescripto-frontend:latest
          imagePullPolicy: Never   # use local Docker image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prescripto-frontend-service
spec:
  selector:
    app: prescripto-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
